config/routes.rb
Rails.application.routes.draw do
  
  get '/employee',  to: 'pages#employee'
  get '/manager',  to: 'pages#manager'
  get '/home', to: 'pages#home'
  
  root 'pages#home'
  
  resources :projects do
    resources :tasks 
  end
  devise_for :employees
end

app/models/task.rb
class Task < ActiveRecord::Base
	#CONSTANTS
	STATUS = ['new', 'inprogress', 'done']
	#VALIDATIONS
    validates_presence_of :name, :description, :project_id#, :status
    validates_inclusion_of :status, in: STATUS, message: "should be from #{STATUS.join(', ')}"
	#ASSOCIATIONS
	belongs_to :employee
	belongs_to :project
    before_save :validate_end_date_time
	#SCOPES
    scope :task_details_for_manager, -> (state) { where(status: state)}

    def validate_end_date_time
		status = self.start_date < self.end_date if start_date.present? && end_date.present?
	    errors.add(:end_date, "cannot be before #{start_date}") if start_date.present? && !status
	    status   
	end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_employee!
  before_action :authorize_rights_for_task, except: [:index]
  # GET /tasks
  # GET /tasks.json
  def index
    @project = Project.find_by(id: params[:project_id])
    @tasks = @project.tasks.where(employee: current_employee) unless current_employee.create_project?
    @tasks = @project.tasks if current_employee.create_project?
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @project = Project.find_by(id: params[:project_id])
    @task = Task.new
    @developers = @project.employees.developers
  end

  # GET /tasks/1/edit
  def edit
    @project = @task.project
    @developers = @project.employees.developers
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    respond_to do |format|
      if @task.save
        format.html { redirect_to project_task_path(@task.project, @task), notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        @project = @task.project
        @developers = @project.employees.developers
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    @project = @task.project
    @developers = @project.employees.developers
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to project_task_path(@task.project, @task), notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        @developers = Employee.developers
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @project = @task.project
    @task.destroy
    respond_to do |format|
      format.html { redirect_to project_tasks_url(@project), notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    def authorize_rights_for_task
      return true if current_employee.super_admin? || @task.project.manager == current_employee || @task.employee == current_employee
      redirect_url = current_employee.admin? ? manager_path : employee_path
      redirect_to redirect_url, alert: 'You are not authorized to view/modify it'
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :description, :employee_id, :project_id, :start_date, :end_date, :status)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_for [@project, @task] do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, required: true %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, required: true %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.datetime_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.datetime_select :end_date %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.select :status, [ ['Status',''] ,['new','new'], ['Inprogress','inprogress'], ['Done', 'done']], required: true%>
  </div>

  <div class="field">
      <label>Assign to Developer: </label><br>
      <%= collection_select(:task, :employee_id, @developers, :id, :name) %>
  </div>

  <%= f.hidden_field :project_id, value: @project.id%>
  <% btn_name = controller.action_name.eql?('new') ? 'Create New Task' : 'Update Task'%>
  <div class="actions">
    <%= f.submit btn_name, class: 'button btn btn-success' %>
    <%= link_to "Back", :back, class: 'btn btn-default' %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1 class="title">Edit Task</h1>

<%= render 'form' %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="title">List of Tasks for <%= @project.name %></h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Status</th>
      <th colspan="3" class="center"> Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.name %></td>
        <td><%= task.description %></td>
        <td><%= task.start_date %></td>
        <td><%= task.end_date %></td>
        <td><%= task.status %></td>
        <td><%= link_to 'Details', project_task_path(@project, task) %></td>

        <td><%= link_to "Edit", edit_project_task_path(@project, task) %></td>
        <% if current_employee.create_project? %>
          <td><%= link_to 'Destroy', project_task_path(@project, task), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_employee.create_project? %>
  <%= link_to 'Create New Task', new_project_task_path, class: 'btn btn-success btn-block' %>
<% end%>  

app/views/tasks/new.html.erb
<h1 class="title">New Task</h1>

<%= render 'form' %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<h1 class="title"> Details of Task</h1>
<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @task.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @task.end_date %>
</p>

<p>
  <strong>Status:</strong>
  <%= @task.status %>
</p>

<p>
  <strong>Developer Name:</strong>
  <%= @task.employee.name %>
</p>

<%= link_to 'Edit', edit_project_task_path(@task.project, @task), class: 'btn btn-primary' %>
<%= link_to 'Back', project_tasks_path(@task.project), class: 'btn btn-default' %>