config/routes.rb
Rails.application.routes.draw do
  
  get '/employee',  to: 'pages#employee'
  get '/manager',  to: 'pages#manager'
  get '/home', to: 'pages#home'
  
  root 'pages#home'
  
  resources :projects do
    resources :tasks 
  end
  devise_for :employees
end

app/models/project.rb
class Project < ActiveRecord::Base
    #VALIDATIONS
    validates_presence_of :name, :description, :manager_id, :location, :client_name
	#CALLBACKS
	before_save :validate_end_date
	# ASSOCIATIONS
	has_and_belongs_to_many :employees#, foreign_key: 'employee_id'
	belongs_to :manager, class_name: 'Employee', foreign_key: 'manager_id'
	has_many :tasks
    
    #INSTANCE METHODS
	def employee_tasks(employee_id)
		self.tasks.where(employee_id: employee_id)
	end

	def validate_end_date
		status = self.start_date <= self.end_date if start_date.present? && end_date.present?
	    errors.add(:end_date, "cannot be before #{start_date}") if start_date.present? && !status
	    status   
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_employee!, :authorize_admin_role
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all if current_employee.super_admin?
    @projects = current_employee.projects if current_employee.admin?
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
    @managers = Employee.managers
    @developers = Employee.developers
  end

  # GET /projects/1/edit
  def edit
    @managers = Employee.managers
    @developers = Employee.developers
  end

  # POST /projects
  # POST /projects.json
  def create
    @managers = Employee.managers
    @developers = Employee.developers
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    @managers = Employee.managers
    @developers = Employee.developers
    can_update_or_destroy
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    can_update_or_destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description, :manager_id, :start_date, :end_date, :location, :client_name, employee_ids: [])
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, required: true %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, required: true %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.date_select :end_date %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location, required: true %>
  </div>
  <div class="field">
    <%= f.label :client_name %><br>
    <%= f.text_field :client_name, required: true %>
  </div>
  <% if (current_employee.super_admin? rescue false) %>
    <div class="field">
      <label>Select Name of Manager: </label><br>
      <%= collection_select(:project, :manager_id, @managers, :id, :name) %>
    </div>
  <% end%>

  <div class="field">
    <%= hidden_field_tag 'project[employee_ids][]', nil%>
    <label>Add developers to project: </label><br>
    <% @developers.each do |dev| %>
    <%= check_box_tag 'project[employee_ids][]', dev.id, @project.employees.include?(dev)%>
    <%= dev.name%><br>
    <%end%>
  </div> 

  <% btn_name = controller.action_name.eql?('new') ? 'Create New Project' : 'Update Project'%>
  <div class="actions">
    <%= f.submit btn_name, class: 'button btn btn-success' %>
    <%= link_to "Back", :back, class: 'btn btn-default' %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1 class="title">Edit Project</h1>

<%= render 'form' %>

app/views/projects/index.html.erb
<h1 class="title">List of Projects</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Location</th>
      <th>Client name</th>
      <th colspan="4" class="center"> Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.description %></td>
        <td><%= project.start_date %></td>
        <td><%= project.end_date %></td>
        <td><%= project.location %></td>
        <td><%= project.client_name %></td>
        <td><%= link_to 'Details', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Manage Tasks', project_tasks_path(project)%> </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Create New Project', new_project_path, class: 'btn btn-success btn-block' %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

app/views/projects/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @project.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @project.end_date %>
</p>

<p>
  <strong>Location:</strong>
  <%= @project.location %>
</p>

<p>
  <strong>Client name:</strong>
  <%= @project.client_name %>
</p>

<p>
  <strong>Manager Name:</strong>
  <%= @project.manager.name %>
</p>

<p>
  <strong>Developer Names:</strong>
  <% @project.employees.each do |dev| %>
    <%= dev.name%>
  <% end %>
</p>

<%= link_to 'Edit', edit_project_path(@project), class: 'btn btn-primary' %>
<%= link_to 'Back', projects_path, class: 'btn btn-default' %>