config/routes.rb
Rails.application.routes.draw do
  
  get '/employee',  to: 'pages#employee'
  get '/manager',  to: 'pages#manager'
  get '/home', to: 'pages#home'
  
  root 'pages#home'
  
  resources :projects do
    resources :tasks 
  end
  devise_for :employees
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(employee)
    # Define abilities for the passed in user here. For example:
    #
      employee ||= Employee.new # guest user (not logged in)
       if employee.role_id == 1
         can [:read, :create], :all
         can [:update, :destroy], Company, :id => employee.company_id
       else
         can :read, :all
         cannot :manage, Employee
       end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/company.rb
class Company < ActiveRecord::Base
	validates :company_name, :registration_id, :start_date, :address, :website, presence: true
	validates :company_name, uniqueness: true 
    
    has_many :employees

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, 
          :validatable
  validates :first_name, :last_name, :gender, :birth_date, :blood_group,  
             :contact_no, :qualification, :joining_date, :department, presence: true;
  has_and_belongs_to_many :projects#, foreign_key: 'project_id'
  has_many :tasks
  scope :managers, -> {where(role: "admin")}
  scope :developers, -> {where(role: "developer")}
  
  def create_project?
    self.admin? || self.super_admin?
  end

  def admin?
  	self.role.eql?('admin')
  end

  def developer?
  	self.role.eql?('developer')
  end

  def super_admin?
  	self.role.eql?('super_admin')
  end

  def name
    self.first_name + " " + self.last_name
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
    #VALIDATIONS
    validates_presence_of :name, :description, :manager_id, :location, :client_name
	#CALLBACKS
	before_save :validate_end_date
	# ASSOCIATIONS
	has_and_belongs_to_many :employees#, foreign_key: 'employee_id'
	belongs_to :manager, class_name: 'Employee', foreign_key: 'manager_id'
	has_many :tasks
    
    #INSTANCE METHODS
	def employee_tasks(employee_id)
		self.tasks.where(employee_id: employee_id)
	end

	def validate_end_date
		status = self.start_date <= self.end_date if start_date.present? && end_date.present?
	    errors.add(:end_date, "cannot be before #{start_date}") if start_date.present? && !status
	    status   
	end
end

app/models/role.rb
class Role < ActiveRecord::Base
	validates :designation, :status, presence: true
    validates :designation, uniqueness: true
    has_many :employees
end

app/models/task.rb
class Task < ActiveRecord::Base
	#CONSTANTS
	STATUS = ['new', 'inprogress', 'done']
	#VALIDATIONS
    validates_presence_of :name, :description, :project_id#, :status
    validates_inclusion_of :status, in: STATUS, message: "should be from #{STATUS.join(', ')}"
	#ASSOCIATIONS
	belongs_to :employee
	belongs_to :project
    before_save :validate_end_date_time
	#SCOPES
    scope :task_details_for_manager, -> (state) { where(status: state)}

    def validate_end_date_time
		status = self.start_date < self.end_date if start_date.present? && end_date.present?
	    errors.add(:end_date, "cannot be before #{start_date}") if start_date.present? && !status
	    status   
	end
end

app/models/work_sheet.rb
class WorkSheet < ActiveRecord::Base
    mount_uploader :attachment, AttachmentUploader
	belongs_to :employee

	validates :project_name, :worked_hours, :work_details, presence: true
    validates :work_details, length: { minimum: 20}
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_employee!, except: [:home]
  
  def employee
    @projects = current_employee.projects
  end

  def manager
  	@projects = current_employee.projects
  	@projects =  Project.all if current_employee.super_admin? 
  	@developers = Employee.developers
  	@states = Task::STATUS
  end

  def home
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_employee!
  before_action :authorize_rights_for_task, except: [:index]
  # GET /tasks
  # GET /tasks.json
  def index
    @project = Project.find_by(id: params[:project_id])
    @tasks = @project.tasks.where(employee: current_employee) unless current_employee.create_project?
    @tasks = @project.tasks if current_employee.create_project?
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @project = Project.find_by(id: params[:project_id])
    @task = Task.new
    @developers = @project.employees.developers
  end

  # GET /tasks/1/edit
  def edit
    @project = @task.project
    @developers = @project.employees.developers
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    respond_to do |format|
      if @task.save
        format.html { redirect_to project_task_path(@task.project, @task), notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        @project = @task.project
        @developers = @project.employees.developers
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    @project = @task.project
    @developers = @project.employees.developers
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to project_task_path(@task.project, @task), notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        @developers = Employee.developers
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @project = @task.project
    @task.destroy
    respond_to do |format|
      format.html { redirect_to project_tasks_url(@project), notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    def authorize_rights_for_task
      return true if current_employee.super_admin? || @task.project.manager == current_employee || @task.employee == current_employee
      redirect_url = current_employee.admin? ? manager_path : employee_path
      redirect_to redirect_url, alert: 'You are not authorized to view/modify it'
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :description, :employee_id, :project_id, :start_date, :end_date, :status)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/practice_helper.rb
module PracticeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/work_sheets_helper.rb
module WorkSheetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EmployeeDailyWork</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  
<meta name="viewport" content="width=device-width, initial-scale=1">

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
<link rel="stylesheet" href="http://twitter.github.com/bootstrap/1.4.0/bootstrap.min.css">


</head>
<body>
<nav class="navbar navbar-default" id="root-nav">
 
  <ul class="nav navbar-nav " >
      <% if employee_signed_in? %>
        <% if current_employee.create_project? %>
          <li ><a href="/manager"/> My Dashbord </a></li>
          <li ><a href="/projects"/> My Project </a></li>
        <% else%>
          <li ><a href="/employee"/> My Dashbord</a></li> 
        <% end%>  
        <li> <%= link_to 'LogOut', destroy_employee_session_path, method: :delete%>
        </li>
      <%else%> 
        <li > <a href="/employees/sign_up"> Sign Up</a></li>
        <li > <a href="/employees/sign_in"> Login</a></li>
       <%end%>
  </ul>
  </nav>
<div class="container">  
  <%if !notice.nil?%>
      <p class="alert alert-success"><%= notice %>
      </p>
  <%end%>
  <%if !alert.nil?%> 
    <p class="alert alert-danger">
      <%= flash[:alert] %>
      </p>
  <%end%>

  <%= yield %>

</div>
<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</body>
</html>

app/views/pages/employee.html.erb
<h1 class="title">List of Tasks Projectwise </h1>

<% count = 1%>
<% @projects.each do |project| %>
  <h1 class="title"><%= count%>. List of Tasks for <%= project.name%> </h1>
  <% count = count + 1%>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Start date</th>
        <th>End date</th>
        <th>Status</th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% tasks = project.employee_tasks(current_employee.id) %>
      <% tasks.each do |task| %>
        <tr>
        	<td><%= task.name %></td>
          <td><%= task.description %></td>
          <td><%= task.start_date %></td>
          <td><%= task.end_date %></td>
          <td><%= task.status %></td>
          <td><%= link_to 'Details', project_task_path(project, task) %></td>
          <td><%= link_to 'Edit', edit_project_task_path(project, task) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
<% end%>

app/views/pages/home.html.erb
<h1 class="title">Home Page</h1>
<p>Welcome to Project Management</p>

app/views/pages/manager.html.erb
<h1 class="title">List of Tasks by Employee</h3>

<table class="table table-bordered">
  <thead>
    <tr border='1px'>
      <th>Status</th>
      <% @developers.each do |dev|%>
        <th> <%= dev.name %></th>
      <% end%>
    </tr>
  </thead>

  <tbody>
  	<% @states.each do |state|%>
	  	<tr>
	  		<td><%= state %></td>
	  		<% @developers.each do |dev|%>
		  		<td>
		  			<% dev.tasks.task_details_for_manager(state).each do |task|%>
		  			    <%= task.name %>
				        <br>
				    <% end%>
		  		</td>
	  		<% end%>
	    </tr>
	<%end %>       
  </tbody>
</table>

<br>

<h1 class="title">List of Tasks by Project</h1>


<table class="table table-bordered">
  <thead>
    <tr>
      <th>Status</th>
      <% @projects.each do |dev|%>
        <th> <%= dev.name %></th>
      <% end%>
    </tr>
  </thead>

  <tbody>
  	<% @states.each do |state|%>
	  	<tr>
	  		<td><%= state %></td>
	  		<% @projects.each do |dev|%>
		  		<td>
		  			<% dev.tasks.task_details_for_manager(state).each do |task|%>
		  			    <%= task.name %>
				        <br>
				    <% end%>
		  		</td>
	  		<% end%>
	    </tr>
	<%end %>       
  </tbody>
</table>